# Generated by Django 2.2.4 on 2019-08-12 12:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationInstance',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_host', models.CharField(help_text='The leftmost part of the domain name of this application', max_length=63)),
                ('spawner', models.CharField(help_text='The spawner used to start the application', max_length=15)),
                ('spawner_application_template_options', models.CharField(help_text='The spawner options at the time the application instance was spawned', max_length=10240)),
                ('spawner_application_instance_id', models.CharField(help_text='An ID that the spawner understands to control and report on the application', max_length=128)),
                ('state', models.CharField(choices=[('SPAWNING', 'Spawning'), ('RUNNING', 'Running'), ('STOPPED', 'Stopped')], default='SPAWNING', max_length=16)),
                ('proxy_url', models.CharField(help_text='The URL that the proxy can proxy HTTP and WebSockets requests to', max_length=256)),
                ('single_running_or_spawning_integrity', models.CharField(help_text='Used internally to avoid duplicate running applications', max_length=63, unique=True)),
            ],
            options={
                'db_table': 'app_applicationinstance',
                'permissions': [('start_all_applications', 'Can start all applications'), ('access_appstream', 'Can access appstream')],
            },
        ),
        migrations.CreateModel(
            name='ApplicationTemplate',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Used in URLs: only lowercase letters allowed', max_length=128, unique=True, validators=[django.core.validators.RegexValidator(regex='^[a-z]+$')])),
                ('nice_name', models.CharField(max_length=128, unique=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9\\- ]+$')])),
                ('spawner', models.CharField(choices=[('PROCESS', 'Process')], default='PROCESS', max_length=10)),
                ('spawner_options', models.CharField(help_text='Options that the spawner understands to start the application', max_length=10240)),
            ],
            options={
                'db_table': 'app_applicationtemplate',
            },
        ),
        migrations.AddIndex(
            model_name='applicationtemplate',
            index=models.Index(fields=['name'], name='app_applica_name_76f0ef_idx'),
        ),
        migrations.AddField(
            model_name='applicationinstance',
            name='application_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applications.ApplicationTemplate'),
        ),
        migrations.AddField(
            model_name='applicationinstance',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='applicationinstance',
            index=models.Index(fields=['owner', 'created_date'], name='app_applica_owner_i_d86479_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationinstance',
            index=models.Index(fields=['public_host', 'state'], name='app_applica_public__48682b_idx'),
        ),
    ]
