# Generated by Django 2.2.4 on 2019-08-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtemplate',
            name='host_pattern',
            field=models.CharField(default='', max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
