# Generated by Django 2.2.4 on 2019-08-24 17:46
import secrets
import string

from django.db import migrations, models


def random_string():
    return ''.join(secrets.choice(string.ascii_lowercase) for i in range(16))


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtemplate',
            name='host_pattern',
            field=models.CharField(default=random_string, max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
