# Generated by Django 2.2.4 on 2019-08-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_applicationtemplate_host_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtemplate',
            name='spawner_time',
            field=models.IntegerField(default=120),
            preserve_default=False,
        ),
    ]
