# Generated by Django 3.0.5 on 2020-04-15 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("applications", "0002_remove_applicationtemplate_host_pattern")]

    operations = [
        migrations.AlterField(
            model_name="applicationtemplate",
            name="name",
            field=models.CharField(
                help_text="Used in URLs: only lowercase letters allowed",
                max_length=128,
                validators=[django.core.validators.RegexValidator(regex="^[a-z]+$")],
            ),
        )
    ]
