# Generated by Django 2.2.4 on 2019-08-27 11:25
from django.db import migrations


def fill_host_pattern_with_uuid(_, __):
    pass
    # ApplicationTemplate.host_pattern has since been removed, so this migration
    # errors when attempted to be run.
    #
    # ApplicationTemplate = apps.get_model('applications', 'ApplicationTemplate')
    # for application_template in ApplicationTemplate.objects.all():
    #     application_template.host_pattern = str(uuid.uuid4())
    #     application_template.save(update_fields=['host_pattern'])


class Migration(migrations.Migration):

    dependencies = [('applications', '0002_applicationtemplate_host_pattern')]

    operations = [
        migrations.RunPython(
            fill_host_pattern_with_uuid, reverse_code=migrations.RunPython.noop
        )
    ]
