# Generated by Django 2.2.4 on 2019-09-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('applications', '0005_applicationtemplate_spawner_time')]

    operations = [
        migrations.AddField(
            model_name='applicationinstance',
            name='cpu',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='applicationinstance',
            name='memory',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
