# Generated by Django 2.2.4 on 2019-09-14 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_auto_20190912_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationInstanceReport',
            fields=[
            ],
            options={
                'verbose_name': 'Application report',
                'verbose_name_plural': 'Application report',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('applications.applicationinstance',),
        ),
    ]
