# Generated by Django 3.0.5 on 2020-05-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("applications", "0007_applicationtemplate_wrap")]

    operations = [
        migrations.AlterField(
            model_name="applicationtemplate",
            name="wrap",
            field=models.CharField(
                choices=[
                    ("NONE", "No wrapping"),
                    ("FULL_HEIGHT_IFRAME", "Wrapped in full height iframe"),
                    (
                        "IFRAME_WITH_VISUALISATIONS_HEADER",
                        "Wrapped in iframe with visualisations header",
                    ),
                ],
                default="NONE",
                max_length=128,
            ),
        )
    ]
