# Generated by Django 3.0.5 on 2020-06-10 13:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("applications", "0008_auto_20200519_1245")]

    operations = [
        migrations.RemoveField(model_name="applicationtemplate", name="user_access_type"),
        migrations.DeleteModel(name="ApplicationTemplateUserPermission"),
    ]
