# Generated by Django 2.2.4 on 2019-09-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('applications', '0008_auto_20190914_0820')]

    operations = [
        migrations.AddField(
            model_name='applicationinstance',
            name='spawner_created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='applicationinstance',
            name='spawner_stopped_at',
            field=models.DateTimeField(null=True),
        ),
    ]
