# Generated by Django 3.0.8 on 2020-07-24 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0009_auto_20200610_1318"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="applicationinstance",
            options={
                "permissions": [
                    ("start_all_applications", "Can start all applications"),
                    ("develop_visualisations", "Can develop visualisations"),
                    ("access_appstream", "Can access appstream"),
                    ("access_quicksight", "Can access AWS QuickSight"),
                ]
            },
        ),
    ]
