# Generated by Django 2.2.4 on 2019-09-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('applications', '0010_auto_20190914_1703')]

    operations = [
        migrations.AddField(
            model_name='applicationinstance',
            name='spawner_cpu',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='applicationinstance',
            name='spawner_memory',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
