# Generated by Django 3.0.8 on 2020-10-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("applications", "0011_auto_20200810_1124")]

    operations = [
        migrations.AlterField(
            model_name="applicationinstance",
            name="spawner_application_instance_id",
            field=models.CharField(
                help_text="An ID that the spawner understands to control and report on the application",
                max_length=10240,
            ),
        )
    ]
