# Generated by Django 3.0.8 on 2020-11-11 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("applications", "0013_auto_20201030_0844"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserToolConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size",
                    models.IntegerField(
                        choices=[
                            (1, "Small"),
                            (2, "Medium (default)"),
                            (3, "Large"),
                            (4, "Extra Large"),
                        ],
                        default=2,
                    ),
                ),
                (
                    "tool_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_tool_configuration",
                        to="applications.ToolTemplate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
