# Generated by Django 3.0.8 on 2021-01-21 15:37

from django.db import migrations, models

from dataworkspace.apps.core.utils import (
    db_role_schema_suffix_for_app,
    db_role_schema_suffix_for_user,
    USER_SCHEMA_STEM,
)


def migrate_existing_application_instance_db_users(apps, _):
    ApplicationInstanceDbUsers = apps.get_model("applications", "ApplicationInstanceDbUsers")
    for db_user in ApplicationInstanceDbUsers.objects.all():
        if db_user.application_instance.application_template.application_type == "TOOL":
            db_role_and_schema_suffix = db_role_schema_suffix_for_user(
                db_user.application_instance.owner
            )
        else:
            db_role_and_schema_suffix = db_role_schema_suffix_for_app(
                db_user.application_instance.application_template
            )

        db_user.db_persistent_role = f"{USER_SCHEMA_STEM}{db_role_and_schema_suffix}"
        db_user.save()


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0015_auto_20201113_1103"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationinstancedbusers",
            name="db_persistent_role",
            field=models.CharField(default="", max_length=256),
            preserve_default=False,
        ),
        migrations.RunPython(
            migrate_existing_application_instance_db_users, migrations.RunPython.noop
        ),
    ]
