# Generated by Django 3.2.11 on 2022-01-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0016_applicationinstancedbusers_db_persistent_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationinstance",
            name="spawner_state",
            field=models.CharField(
                choices=[("RUNNING", "Running"), ("STOPPED", "Stopped")],
                default="RUNNING",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="applicationinstance",
            name="spawner_state_refreshed_at",
            field=models.DateTimeField(
                help_text="When the state of the spawner was last refreshed", null=True
            ),
        ),
    ]
