# Generated by Django 3.2.5 on 2021-10-04 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0016_applicationinstancedbusers_db_persistent_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationinstance',
            name='impersonated_user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='application_instances',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
