# Generated by Django 3.2.11 on 2022-02-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0016_applicationinstancedbusers_db_persistent_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationtemplate",
            name="group_name",
            field=models.TextField(
                blank=True,
                choices=[
                    ("VISUALISATIONS", "Visualisation Tools"),
                    ("ANALYSIS", "Data Analysis Tools"),
                    ("MANAGEMENT", "Data Management Tools"),
                    ("IDE", "Integrated Development Environments"),
                ],
                null=True,
            ),
        ),
    ]
