# Generated by Django 3.0.3 on 2020-03-04 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('applications', '0017_auto_20200221_1734')]

    operations = [
        migrations.CreateModel(
            name='ToolTemplate',
            fields=[],
            options={
                'verbose_name': 'Tool',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('applications.applicationtemplate',),
        )
    ]
