# Generated by Django 3.2.11 on 2022-02-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0017_applicationtemplate_group_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationtemplate",
            name="group_name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("VISUALISATIONS", "Visualisation Tools"),
                    ("ANALYSIS", "Data Analysis Tools"),
                    ("MANAGEMENT", "Data Management Tools"),
                    ("IDE", "Integrated Development Environments"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
