# Generated by Django 3.0.3 on 2020-03-06 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('applications', '0018_tooltemplate')]

    operations = [
        migrations.AlterUniqueTogether(
            name='applicationtemplate', unique_together=set()
        )
    ]
