# Generated by Django 3.0.3 on 2020-03-06 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('applications', '0019_auto_20200306_1126')]

    operations = [
        migrations.RemoveField(model_name='applicationtemplate', name='host_pattern')
    ]
