# Generated by Django 3.2.20 on 2023-10-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0023_applicationinstance_app_applica_state_9beedf_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationinstance",
            name="successfully_started_at",
            field=models.DateTimeField(null=True),
        ),
    ]
