# Generated by Django 3.2.20 on 2023-10-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0024_applicationinstance_successfully_started_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationtemplate",
            name="include_in_dw_stats",
            field=models.BooleanField(default=False),
        ),
    ]
