# Generated by Django 4.2.16 on 2024-11-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0026_alter_usertoolconfiguration_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertoolconfiguration",
            name="size",
            field=models.IntegerField(
                choices=[
                    (1, "Small"),
                    (2, "Medium"),
                    (3, "Large"),
                    (4, "Extra Large"),
                    (5, "2x Extra Large"),
                    (6, "3x Extra Large"),
                ],
                default=2,
            ),
        ),
    ]
