# Generated by Django 4.2.16 on 2024-11-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0027_alter_usertoolconfiguration_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationtemplate",
            name="tag",
            field=models.CharField(
                blank=True,
                help_text="The text of a short tag displayed next to the tool on the tools page. This would typically be used to highlight if a tool is new, recommended, or deprecated.",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="applicationtemplate",
            name="tag_extra_css_class",
            field=models.CharField(
                blank=True,
                help_text="A CSS class applied to the tag if present. This would typically be one of the govuk-tag--* classes used to style the tag component from the GOV.UK Design System.",
                max_length=128,
                verbose_name="Tag class",
            ),
        ),
    ]
