# Generated by Django 4.2.18 on 2025-02-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0028_applicationtemplate_tag_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="visualisationapproval",
            name="approver_type",
            field=models.CharField(
                choices=[
                    ("OWNER", "Owner"),
                    ("PEER_REVIEWER", "Peer-reviewer"),
                    ("TEAM_MEMBER", "Team Member"),
                ],
                default="OWNER",
            ),
        ),
    ]
