# Generated by Django 4.2.20 on 2025-03-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0028_applicationtemplate_tag_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="visualisationapproval",
            name="approval_date",
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="visualisationapproval",
            name="approval_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("owner", "Owner"),
                    ("peer_reviewer", "Peer Reviewer"),
                    ("team_member", "Team Member"),
                ],
                default=None,
                null=True,
            ),
        ),
    ]
