# Generated by Django 4.2.20 on 2025-04-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0029_visualisationapproval_approval_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visualisationapproval",
            name="approval_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("owner", "owner"),
                    ("peer reviewer", "peer reviewer"),
                    ("team member", "team member"),
                ],
                default=None,
                null=True,
            ),
        ),
    ]
