# Generated by Django 4.2.18 on 2025-02-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0029_visualisationapproval_approver_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visualisationapproval",
            name="approver_type",
            field=models.CharField(
                choices=[
                    ("Owner", "Owner"),
                    ("Peer-reviewer", "Peer-reviewer"),
                    ("Team Member", "Team Member"),
                ],
                default="Owner",
            ),
        ),
    ]
