# Generated by Django 3.2.16 on 2022-12-19 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.migrations.operations.special
import django.db.models.deletion
import uuid


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# dataworkspace.apps.accounts.migrations.0004_profile_first_login


def migrate_existing_users_fist_login(apps, _):
    model = apps.get_model("accounts", "Profile")
    for profile in model.objects.all():
        profile.first_login = profile.user.date_joined
        profile.save()


class Migration(migrations.Migration):

    replaces = [
        ("accounts", "0001_initial"),
        ("accounts", "0002_profile_home_directory_efs_access_point_id"),
        ("accounts", "0003_profile_tools_access_role_arn"),
        ("accounts", "0004_profile_first_login"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sso_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "home_directory_efs_access_point_id",
                    models.CharField(max_length=128, null=True, unique=True),
                ),
                ("tools_access_role_arn", models.TextField(blank=True, default="")),
                ("first_login", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "app_profile",
            },
        ),
        migrations.RunPython(
            migrate_existing_users_fist_login, reverse_code=migrations.RunPython.noop
        ),
    ]
