# Generated by Django 3.0.8 on 2020-07-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="home_directory_efs_access_point_id",
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
