# Generated by Django 3.2.12 on 2022-05-18 11:35

from django.db import migrations, models


def migrate_existing_users_fist_login(apps, _):
    model = apps.get_model("accounts", "Profile")
    for profile in model.objects.all():
        profile.first_login = profile.user.date_joined
        profile.save()


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_profile_tools_access_role_arn"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="first_login",
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(
            migrate_existing_users_fist_login, reverse_code=migrations.RunPython.noop
        ),
    ]
