# Generated by Django 3.2.19 on 2023-05-11 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_auto_20230511_1615"),
        ("accounts", "0004_profile_first_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="core.dataworkspaceuser"
            ),
        ),
    ]
