# Generated by Django 3.2.19 on 2023-05-12 13:40

from django.db import migrations

from dataworkspace.apps.core.models import get_user_model


def migrate_username_to_sso_id(apps, schema_editor):
    dw_users = get_user_model()
    for user in dw_users.objects.all():
        if hasattr(user, "profile") and user.profile.sso_id:
            user.username = user.profile.sso_id
            user.save()


def unmigrate_username_to_sso_id(apps, schema_editor):
    dw_users = get_user_model()
    for user in dw_users.objects.all():
        user.username = user.email
        user.save()


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_profile_user"),
    ]

    operations = [
        migrations.RunPython(
            migrate_username_to_sso_id, reverse_code=unmigrate_username_to_sso_id
        ),
    ]
