# Generated by Django 3.2.19 on 2023-05-12 13:40

from django.db import IntegrityError, migrations

from dataworkspace.apps.accounts.models import Profile
from dataworkspace.apps.core.models import get_user_model


def migrate_username_to_sso_id(apps, schema_editor):
    dw_users = get_user_model()
    for user in dw_users.objects.all():
        try:
            profile = user.profile
        except Profile.DoesNotExist:
            print(f"Skipping user {user.email} as they have no profile")
            continue
        if profile.sso_id is not None:
            user.username = profile.sso_id
            try:
                user.save()
            except IntegrityError:
                print(f"Skipping user {user.email} as they have duplicate accounts")


def unmigrate_username_to_sso_id(apps, schema_editor):
    dw_users = get_user_model()
    for user in dw_users.objects.all():
        user.username = user.email
        try:
            user.save()
        except IntegrityError:
            print(f"Skipping user {user.email} as they have duplicate accounts")


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_profile_user"),
    ]

    operations = [
        migrations.RunPython(
            migrate_username_to_sso_id, reverse_code=unmigrate_username_to_sso_id
        ),
    ]
