# Generated by Django 3.2.19 on 2023-05-26 13:36

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_alter_dataworkspaceuser_options"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("accounts", "0006_migrate_username_to_sso_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDataTableView",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("source_object_id", models.TextField()),
                (
                    "visible_columns",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=256),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("sort_column", models.CharField(blank=True, max_length=256, null=True)),
                ("sort_direction", models.CharField(blank=True, max_length=20, null=True)),
                ("filters", models.JSONField(blank=True, null=True)),
                (
                    "source_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_grid_views",
                        to="core.dataworkspaceuser",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "source_content_type", "source_object_id")},
            },
        ),
    ]
