# Generated by Django 3.2.19 on 2023-05-31 16:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_alter_profile_user"),
        ("accounts", "0007_userdatatableview"),
    ]

    operations = []
