# Generated by Django 3.2.19 on 2023-05-31 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0008_merge_0007_alter_profile_user_0007_userdatatableview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdatatableview",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_grid_views",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
