# Generated by Django 3.2.19 on 2023-06-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_auto_20230601_1633"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="sso_status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                max_length=256,
            ),
        ),
    ]
