# Generated by Django 4.2.11 on 2024-06-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_profile_sso_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="certification_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
