# Generated by Django 4.2.11 on 2024-06-17 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_profile_certification_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="certification_date",
            new_name="tools_certification_date",
        ),
    ]
