# Generated by Django 4.2.11 on 2024-07-15 15:31

from django.db import migrations
from django.contrib.auth.models import Permission


def remove_tools_access(apps, schema_editor):
    user_model = apps.get_model("auth", "User")

    permissions_codenames = [
        "start_all_applications",
        "develop_visualisations",
        "access_quicksight",
        "access_appstream",
    ]
    permission_ids = Permission.objects.filter(codename__in=permissions_codenames).all()

    for user in user_model.objects.all():
        matching_user_permissions = user.user_permissions.filter(
            codename__in=permissions_codenames
        ).exists()
        if matching_user_permissions:
            print(f"User {user.username} has tools permissions")
            for permission_id in permission_ids:
                user.user_permissions.remove(permission_id.id)
            print(f"Removed tools access for user {user.username}")
        else:
            print(f"User {user.username} doesn't have tools permissions")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_rename_certification_date_profile_tools_certification_date"),
    ]

    operations = [
        migrations.RunPython(remove_tools_access, reverse_code=migrations.RunPython.noop),
    ]
