# Generated by Django 4.2.15 on 2024-09-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_disable_tools"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_renewal_email_sent",
            field=models.BooleanField(default=False),
        ),
    ]
