# Generated by Django 4.2.15 on 2024-09-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_disable_tools"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bookmarks",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="recent_collections",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="recent_items",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="recent_tools",
            field=models.BooleanField(default=True),
        ),
    ]
