# Generated by Django 4.2.15 on 2024-09-18 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_profile_bookmarks_profile_recent_collections_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="bookmarks",
            new_name="show_bookmarks",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="recent_collections",
            new_name="show_recent_collections",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="recent_items",
            new_name="show_recent_items",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="recent_tools",
            new_name="show_recent_tools",
        ),
    ]
