# Generated by Django 4.2.15 on 2024-09-17 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0015_profile_bookmarks_profile_recent_collections_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="bookmarks",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="recent_collections",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="recent_items",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="recent_tools",
        ),
        migrations.CreateModel(
            name="HomePageProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bookmarks", models.BooleanField(default=True)),
                ("recent_collections", models.BooleanField(default=True)),
                ("recent_items", models.BooleanField(default=True)),
                ("recent_tools", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "app_homepage_profile",
            },
        ),
    ]
