# Generated by Django 3.0.7 on 2020-08-25 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0010_auto_20200429_1250'),
    ]

    operations = [
        migrations.RemoveField(model_name='query', name='snapshot',),
    ]
