# Generated by Django 3.0.8 on 2020-10-20 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("explorer", "0011_remove_query_snapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaygroundSQL",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("sql", models.TextField()),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
