# Generated by Django 3.0.8 on 2020-12-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("explorer", "0013_auto_20201222_1538"),
    ]

    operations = [
        migrations.AddField(
            model_name="querylog",
            name="error",
            field=models.TextField(blank=True, null=True),
        ),
    ]
