# Generated by Django 3.2.5 on 2021-10-02 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('explorer', '0015_auto_20210104_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='querylog',
            name='impersonator',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='querylog',
            name='run_by_user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='query_logs',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
