# Generated by Django 3.2.12 on 2022-04-01 15:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("explorer", "0018_chartbuilderchart_thumbnail"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChartBuilderChart",
        ),
    ]
