# Generated by Django 3.2.19 on 2023-05-12 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_migrate_auth_user_model"),
        ("explorer", "0020_alter_querylog_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playgroundsql",
            name="created_by_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.dataworkspaceuser"
            ),
        ),
        migrations.AlterField(
            model_name="query",
            name="created_by_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.dataworkspaceuser",
            ),
        ),
        migrations.AlterField(
            model_name="querylog",
            name="run_by_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.dataworkspaceuser",
            ),
        ),
    ]
