# Generated by Django 3.0.8 on 2021-01-20 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="data_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requester_role",
                    models.CharField(
                        choices=[
                            ("IAO", "Information Asset Owner"),
                            ("IAM", "Information Asset Manager"),
                            (
                                "delegate",
                                "A colleague delegated by the owner or manager",
                            ),
                            ("other", "Someone else"),
                        ],
                        max_length=256,
                    ),
                ),
                (
                    "name_of_owner_or_manager",
                    models.CharField(blank=True, max_length=256),
                ),
                ("data_description", models.TextField()),
                ("data_purpose", models.TextField()),
                ("data_location", models.TextField(blank=True)),
                (
                    "security_classification",
                    models.CharField(
                        choices=[
                            ("official", "Official (includes public data)"),
                            ("commercially-sensitive", "Official-Sensitive Commercial"),
                            ("personal", "Official-Sensitive Personal"),
                            (
                                "locsen",
                                "Official-Sensitive LocSen (location sensitive)",
                            ),
                            ("secret", "Secret"),
                            ("top-secret", "Top secret"),
                            ("unknown", "I don’t know"),
                        ],
                        max_length=256,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("submitted", "Submitted")],
                        default="draft",
                        max_length=256,
                    ),
                ),
                ("zendesk_ticket_id", models.CharField(max_length=256)),
            ],
            options={"abstract": False},
        ),
    ]
