# Generated by Django 3.0.8 on 2021-02-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("request_data", "0003_auto_20210126_1318"),
    ]

    operations = [
        migrations.AddField(
            model_name="datarequest",
            name="data_licence",
            field=models.TextField(blank=True),
        ),
    ]
