version: "3.4"
services:
  data-workspace-superset:
     build:
       context: superset
       dockerfile: Dockerfile
       target: dev
     image: data-workspace-superset
     environment:
       DB_USER: postgres
       DB_PASSWORD: postgres
       DB_HOST: data-workspace-postgres
       DB_NAME: superset
       DB_PORT: 5432
     env_file:
       - .envs/superset.dev.env
     volumes:
       - ./superset/superset_config.py:/etc/superset/superset_config.py

networks:
  default:
    external:
      name: data-infrastructure-shared-network
