# Generated by Django 4.2.14 on 2024-08-07 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("applications", "0025_applicationtemplate_include_in_dw_stats"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArangoUser",
            fields=[
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(db_index=True, max_length=256)),
                ("deleted_date", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arango_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("created_date",),
            },
        ),
        migrations.CreateModel(
            name="ApplicationInstanceArangoUsers",
            fields=[
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("db_username", models.CharField(max_length=256)),
                (
                    "application_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.applicationinstance",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["db_username"], name="arangodb_ap_db_user_793637_idx")
                ],
            },
        ),
    ]
