# Generated by Django 4.2.7 on 2024-04-26 10:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("datasets", "0168_sourcegraphcollection"),
        ("arangodb", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceGraphCollectionFieldDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        max_length=63,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^[a-zA-Z][a-zA-Z0-9_\\.]*$"
                            )
                        ],
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=1024, null=True)),
                (
                    "source_collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_definitions",
                        to="datasets.sourcegraphcollection",
                    ),
                ),
            ],
            options={
                "unique_together": {("field", "source_collection")},
            },
        ),
    ]
