# Generated by Django 4.2.14 on 2024-07-29 14:08

import dataworkspace.apps.core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("arangodb", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArangoTeam",
            fields=[
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=256, unique=True)),
                ("database_name", models.CharField(max_length=63, unique=True)),
                (
                    "notes",
                    dataworkspace.apps.core.models.RichTextField(blank=True, null=True),
                ),
            ],
            options={
                "verbose_name": "ArangoTeam",
                "verbose_name_plural": "ArangoTeams",
            },
        ),
        migrations.CreateModel(
            name="ArangoTeamMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="arangodb.arangoteam",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("team_id", "user_id")},
            },
        ),
        migrations.AddField(
            model_name="arangoteam",
            name="member",
            field=models.ManyToManyField(
                through="arangodb.ArangoTeamMembership", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
