# Generated by Django 4.2.14 on 2024-08-09 16:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("datasets", "0173_arangodocumentcollection"),
        ("arangodb", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArangoDocumentCollectionFieldDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        max_length=63,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^[a-zA-Z][a-zA-Z0-9_\\.]*$"
                            )
                        ],
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "arango_collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_definitions",
                        to="datasets.arangodocumentcollection",
                    ),
                ),
            ],
            options={
                "unique_together": {("field", "arango_collection")},
            },
        ),
    ]
