# Generated by Django 3.2.16 on 2022-12-19 11:40

import ckeditor.fields
import dataworkspace.apps.core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [
        ("data_collections", "0001_initial"),
        ("data_collections", "0002_collection_published"),
        ("data_collections", "0003_auto_20221027_1238"),
        ("data_collections", "0004_auto_20221027_1239"),
        ("data_collections", "0005_rename_uuid_collection_id"),
        ("data_collections", "0006_auto_20221031_1229"),
        ("data_collections", "0007_alter_collectiondatasetmembership_options"),
        ("data_collections", "0008_auto_20221031_1614"),
        ("data_collections", "0009_rename_catalogues_collection_visualisation_catalogue_items"),
        ("data_collections", "0010_auto_20221102_0955"),
        ("data_collections", "0011_auto_20221103_1655"),
        ("data_collections", "0012_auto_20221103_1721"),
        ("data_collections", "0013_remove_collection_published"),
        ("data_collections", "0013_collection_notes"),
        ("data_collections", "0014_merge_20221109_1054"),
        ("data_collections", "0015_auto_20221114_1428"),
        ("data_collections", "0016_alter_collectionusermembership_collection"),
        ("data_collections", "0015_alter_collection_notes"),
        ("data_collections", "0017_merge_20221115_1526"),
        ("data_collections", "0018_alter_collection_notes"),
        ("data_collections", "0019_alter_collectionusermembership_user"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("datasets", "0128_auto_20220616_1649"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("published", models.BooleanField(default=False)),
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name": "Collection",
                "verbose_name_plural": "Collections",
            },
        ),
        migrations.CreateModel(
            name="CollectionDatasetMembership",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collections",
                        to="data_collections.collection",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datasets",
                        to="datasets.dataset",
                    ),
                ),
            ],
            options={
                "unique_together": {("dataset_id", "collection_id")},
                "ordering": ("id",),
            },
        ),
        migrations.AddField(
            model_name="collection",
            name="datasets",
            field=models.ManyToManyField(
                through="data_collections.CollectionDatasetMembership", to="datasets.DataSet"
            ),
        ),
        migrations.AlterField(
            model_name="collectiondatasetmembership",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dataset_collections",
                to="data_collections.collection",
            ),
        ),
        migrations.CreateModel(
            name="CollectionVisualisationCatalogueItemMembership",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visualisation_collections",
                        to="data_collections.collection",
                    ),
                ),
                (
                    "visualisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visualisation",
                        to="datasets.visualisationcatalogueitem",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("deleted", models.BooleanField(default=False)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
                "unique_together": {("visualisation", "collection_id")},
            },
        ),
        migrations.AddField(
            model_name="collection",
            name="visualisation_catalogue_items",
            field=models.ManyToManyField(
                through="data_collections.CollectionVisualisationCatalogueItemMembership",
                to="datasets.VisualisationCatalogueItem",
            ),
        ),
        migrations.AddField(
            model_name="collectiondatasetmembership",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="collectiondatasetmembership",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="collectiondatasetmembership",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="collectiondatasetmembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", False)),
                fields=("dataset_id", "collection_id"),
                name="unique_dataset_if_not_deleted",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionvisualisationcatalogueitemmembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", False)),
                fields=("visualisation", "collection_id"),
                name="unique_visualisation_if_not_deleted",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="collectiondatasetmembership",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="collectionvisualisationcatalogueitemmembership",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="collection",
            name="published",
        ),
        migrations.AddField(
            model_name="collection",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="CollectionUserMembership",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_collections",
                        to="data_collections.collection",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.AddConstraint(
            model_name="collectionusermembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", False)),
                fields=("user_id", "collection_id"),
                name="unique_user_if_not_deleted",
            ),
        ),
        migrations.AlterField(
            model_name="collectionusermembership",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_memberships",
                to="data_collections.collection",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="notes",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="collection",
            name="notes",
            field=dataworkspace.apps.core.models.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="collectionusermembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collection_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
