# Generated by Django 3.2.15 on 2022-10-25 16:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datasets", "0128_auto_20220616_1649"),
        ("data_collections", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="datasets",
            field=models.ManyToManyField(
                blank=True, related_name="datasets", to="datasets.DataSet"
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="collection",
            name="published_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="collection",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="collection",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
