# Generated by Django 3.2.15 on 2022-10-27 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_collections", "0002_collection_published"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collection",
            name="slug",
        ),
    ]
