# Generated by Django 3.2.15 on 2022-10-27 12:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("data_collections", "0002_collection_published"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collection",
            name="slug",
        ),
        migrations.AddField(
            model_name="collection",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
