# Generated by Django 3.2.15 on 2022-10-27 12:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("data_collections", "0003_auto_20221027_1238"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collection",
            name="id",
        ),
        migrations.AlterField(
            model_name="collection",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
