# Generated by Django 3.2.15 on 2022-10-31 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("datasets", "0128_auto_20220616_1649"),
        ("data_collections", "0007_alter_collectiondatasetmembership_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectiondatasetmembership",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dataset_collections",
                to="data_collections.collection",
            ),
        ),
        migrations.CreateModel(
            name="CollectionVisualisationCatalogueItemMembership",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visualisation_collections",
                        to="data_collections.collection",
                    ),
                ),
                (
                    "visualisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visualisation",
                        to="datasets.visualisationcatalogueitem",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
                "unique_together": {("visualisation", "collection_id")},
            },
        ),
        migrations.AddField(
            model_name="collection",
            name="catalogues",
            field=models.ManyToManyField(
                through="data_collections.CollectionVisualisationCatalogueItemMembership",
                to="datasets.VisualisationCatalogueItem",
            ),
        ),
    ]
