# Generated by Django 3.2.15 on 2022-11-03 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_collections", "0011_auto_20221103_1655"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="collectiondatasetmembership",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="collectionvisualisationcatalogueitemmembership",
            unique_together=set(),
        ),
    ]
