# Generated by Django 3.2.16 on 2022-11-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_collections", "0012_auto_20221103_1721"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
