# Generated by Django 3.2.15 on 2022-11-08 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_collections', '0012_auto_20221103_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='published',
        ),
    ]
