# Generated by Django 3.2.16 on 2022-11-09 10:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_collections", "0013_collection_notes"),
        ("data_collections", "0013_remove_collection_published"),
    ]

    operations = []
