# Generated by Django 3.2.15 on 2022-11-10 11:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_collections", "0014_merge_20221109_1054"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="notes",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
