# Generated by Django 3.2.13 on 2022-11-14 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_collections", "0015_auto_20221114_1428"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionusermembership",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_memberships",
                to="data_collections.collection",
            ),
        ),
    ]
