# Generated by Django 3.2.16 on 2022-11-15 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_collections', '0015_alter_collection_notes'),
        ('data_collections', '0016_alter_collectionusermembership_collection'),
    ]

    operations = [
    ]
