# Generated by Django 3.2.16 on 2022-11-21 17:05

from django.db import migrations
import dataworkspace.apps.core.models


class Migration(migrations.Migration):
    dependencies = [
        ("data_collections", "0017_merge_20221115_1526"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="notes",
            field=dataworkspace.apps.core.models.RichTextField(blank=True, null=True),
        ),
    ]
