# Generated by Django 3.2.16 on 2022-11-25 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("data_collections", "0018_alter_collection_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionusermembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collection_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
