# Generated by Django 3.2.19 on 2023-05-12 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_migrate_auth_user_model"),
        ("data_collections", "0020_alter_collectionusermembership_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created+",
                to="core.dataworkspaceuser",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.dataworkspaceuser",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated+",
                to="core.dataworkspaceuser",
            ),
        ),
        migrations.AlterField(
            model_name="collectiondatasetmembership",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created+",
                to="core.dataworkspaceuser",
            ),
        ),
        migrations.AlterField(
            model_name="collectiondatasetmembership",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated+",
                to="core.dataworkspaceuser",
            ),
        ),
        migrations.AlterField(
            model_name="collectionusermembership",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created+",
                to="core.dataworkspaceuser",
            ),
        ),
        migrations.AlterField(
            model_name="collectionusermembership",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated+",
                to="core.dataworkspaceuser",
            ),
        ),
        migrations.AlterField(
            model_name="collectionvisualisationcatalogueitemmembership",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created+",
                to="core.dataworkspaceuser",
            ),
        ),
        migrations.AlterField(
            model_name="collectionvisualisationcatalogueitemmembership",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated+",
                to="core.dataworkspaceuser",
            ),
        ),
    ]
