# Generated by Django 3.2.19 on 2023-07-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_collections", "0022_auto_20230531_1549"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="user_access_type",
            field=models.CharField(
                choices=[
                    ("REQUIRES_AUTHENTICATION", "All logged in users"),
                    ("REQUIRES_AUTHORIZATION", "Only specific authorized users or email domains"),
                ],
                default="REQUIRES_AUTHORIZATION",
                max_length=64,
            ),
        ),
    ]
