# Generated by Django 3.2.19 on 2023-07-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_collections", "0023_collection_user_access_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="user_access_type",
            field=models.CharField(
                choices=[
                    ("REQUIRES_AUTHENTICATION", "All logged in users"),
                    ("REQUIRES_AUTHORIZATION", "Only specific authorized users or email domains"),
                ],
                default="REQUIRES_AUTHENTICATION",
                max_length=64,
            ),
        ),
    ]
