# Generated by Django 4.2.14 on 2024-07-25 12:47

import dataworkspace.apps.core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_collections", "0024_alter_collection_user_access_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="description",
            field=dataworkspace.apps.core.models.RichTextField(blank=True, null=True),
        ),
    ]
