# Generated by Django 2.2.3 on 2019-08-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventlog',
            options={'get_latest_by': 'timestamp', 'ordering': ('-timestamp',)},
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='event_type',
            field=models.IntegerField(choices=[(1, 'Dataset source link download'), (2, 'Dataset source table download'), (3, 'Reference dataset download'), (4, 'Table data download')]),
        ),
    ]
