# Generated by Django 3.2.4 on 2021-09-30 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventlog', '0014_alter_eventlog_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='impersonated_user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
