# Generated by Django 3.2.19 on 2023-05-11 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_auto_20230511_1615"),
        ("eventlog", "0032_alter_eventlog_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventlog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="core.dataworkspaceuser",
            ),
        ),
    ]
