# Generated by Django 3.2.19 on 2023-05-31 16:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eventlog", "0034_alter_eventlog_event_type"),
        ("eventlog", "0034_alter_eventlog_user"),
    ]

    operations = []
