# Generated by Django 3.2.20 on 2023-10-17 13:23

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("eventlog", "0042_alter_eventlog_event_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemStatLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "type",
                    models.IntegerField(
                        choices=[(1, "Runtime to generate tool table permissions for a user")]
                    ),
                ),
                ("stat", models.FloatField(null=True)),
                ("object_id", models.CharField(max_length=255, null=True)),
                (
                    "extra",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder, null=True
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ("-timestamp",),
                "get_latest_by": "timestamp",
            },
        ),
    ]
