# Generated by Django 3.2.20 on 2023-10-18 09:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eventlog", "0043_systemstatlog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="systemstatlog",
            options={
                "get_latest_by": "timestamp",
                "ordering": ("-timestamp",),
                "verbose_name_plural": "System stats",
            },
        ),
    ]
