# Generated by Django 4.2.7 on 2024-01-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MaintenanceSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("maintenance_text", models.CharField()),
                ("maintenance_toggle", models.BooleanField()),
            ],
            options={
                "verbose_name_plural": "settings",
            },
        ),
    ]
