# Generated by Django 4.2.7 on 2024-01-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maintenance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenancesettings",
            name="contact_email",
            field=models.EmailField(default="", max_length=254),
            preserve_default=False,
        ),
    ]
