# Generated by Django 4.2.7 on 2024-01-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maintenance", "0002_maintenancesettings_contact_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenancesettings",
            name="maintenance_text",
            field=models.CharField(
                help_text="This is the main content of the maintenance page. You can use HTML &lt;br&gt; tags to format the text."
            ),
        ),
    ]
