# Generated by Django 4.2.15 on 2025-01-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NotificationBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("banner_text", models.CharField()),
                ("banner_toggle", models.BooleanField()),
                ("banner_time", models.DateTimeField()),
            ],
            options={
                "verbose_name_plural": "settings",
            },
        ),
    ]
