# Generated by Django 4.2.18 on 2025-01-27 14:05

import dataworkspace.apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NotificationBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("campaign_name", models.TextField()),
                ("content", dataworkspace.apps.core.models.RichTextField()),
                (
                    "last_chance_content",
                    dataworkspace.apps.core.models.RichTextField(
                        blank=True,
                        help_text="(Optional) Message to run within 'last_chance_days' window.               Will be shown to users that have dismissed or not engaged with the banner.",
                        null=True,
                    ),
                ),
                (
                    "last_chance_days",
                    models.IntegerField(
                        blank=True,
                        help_text="(Optional) Days remaining to run 'last chance message'.",
                        null=True,
                    ),
                ),
                ("end_date", models.DateField()),
                ("published", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "Notification Banner",
            },
        ),
    ]
