# Generated by Django 4.2.15 on 2025-01-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification_banner", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notificationbanner",
            old_name="banner_toggle",
            new_name="banner_live",
        ),
        migrations.RemoveField(
            model_name="notificationbanner",
            name="banner_time",
        ),
        migrations.AddField(
            model_name="notificationbanner",
            name="banner_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationbanner",
            name="banner_link",
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name="notificationbanner",
            name="banner_link_text",
            field=models.CharField(blank=True),
        ),
    ]
