# Generated by Django 4.2.15 on 2025-01-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notification_banner",
            "0002_rename_banner_toggle_notificationbanner_banner_live_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationbanner",
            name="banner_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="notificationbanner",
            name="banner_link",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="notificationbanner",
            name="banner_link_text",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="notificationbanner",
            name="banner_live",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="notificationbanner",
            name="banner_text",
            field=models.CharField(max_length=255),
        ),
    ]
