# Generated by Django 4.2.15 on 2025-01-23 09:47

import dataworkspace.apps.core.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notification_banner",
            "0003_alter_notificationbanner_banner_end_date_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="notificationbanner",
            old_name="banner_live",
            new_name="published",
        ),
        migrations.RemoveField(
            model_name="notificationbanner",
            name="banner_end_date",
        ),
        migrations.RemoveField(
            model_name="notificationbanner",
            name="banner_link",
        ),
        migrations.RemoveField(
            model_name="notificationbanner",
            name="banner_link_text",
        ),
        migrations.RemoveField(
            model_name="notificationbanner",
            name="banner_text",
        ),
        migrations.AddField(
            model_name="notificationbanner",
            name="content",
            field=dataworkspace.apps.core.models.RichTextField(default="blah"),
        ),
        migrations.AddField(
            model_name="notificationbanner",
            name="end_date",
            field=models.DateField(
                default=datetime.datetime(2025, 1, 23, 9, 47, 48, 730386)
            ),
        ),
    ]
