# Generated by Django 4.2.15 on 2025-01-23 09:50
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notification_banner",
            "0004_rename_banner_live_notificationbanner_published_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationbanner",
            name="end_date",
            field=models.DateField(),
        ),
    ]
