# Generated by Django 4.2.18 on 2025-01-23 13:44

from django.db import migrations, models

import dataworkspace.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ("notification_banner", "0006_alter_notificationbanner_end_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notificationbanner",
            options={"verbose_name_plural": "Notification Banner"},
        ),
        migrations.AddField(
            model_name="notificationbanner",
            name="campaign_name",
            field=models.TextField(default="def"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="notificationbanner",
            name="content",
            field=dataworkspace.apps.core.models.RichTextField(),
        ),
        migrations.AlterField(
            model_name="notificationbanner",
            name="end_date",
            field=models.DateField(),
        ),
    ]
