# Generated by Django 4.2.15 on 2025-01-27 11:01

import dataworkspace.apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification_banner", "0006_alter_notificationbanner_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationbanner",
            name="content",
            field=dataworkspace.apps.core.models.RichTextField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="notificationbanner",
            name="end_date",
            field=models.DateField(default=False, null=True),
        ),
    ]
