# Generated by Django 4.2.18 on 2025-01-24 11:08

from django.db import migrations, models

import dataworkspace.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ("notification_banner", "0007_alter_notificationbanner_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationbanner",
            name="last_chance_days",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="notificationbanner",
            name="last_chance_message",
            field=dataworkspace.apps.core.models.RichTextField(default=""),
        ),
    ]
