# Generated by Django 4.2.18 on 2025-01-24 16:30

import dataworkspace.apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification_banner", "0008_notificationbanner_last_chance_days_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notificationbanner",
            name="last_chance_message",
        ),
        migrations.AddField(
            model_name="notificationbanner",
            name="last_chance_content",
            field=dataworkspace.apps.core.models.RichTextField(
                blank=True,
                help_text="(Optional) Message to run within 'last_chance_days' window. Will be shown to users that have dismissed or not engaged with the banner.",
            ),
        ),
        migrations.AlterField(
            model_name="notificationbanner",
            name="last_chance_days",
            field=models.IntegerField(
                blank=True,
                help_text="(Optional) Days remaining to run 'last chance message'.",
            ),
        ),
    ]
