# Generated by Django 4.2.18 on 2025-01-27 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notification_banner", "0007_alter_notificationbanner_content_and_more"),
        (
            "notification_banner",
            "0010_alter_notificationbanner_last_chance_content_and_more",
        ),
    ]

    operations = []
