# Generated by Django 4.2.18 on 2025-01-27 12:11

import dataworkspace.apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification_banner", "0011_merge_20250127_1156"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationbanner",
            name="content",
            field=dataworkspace.apps.core.models.RichTextField(default="default"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="notificationbanner",
            name="end_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="notificationbanner",
            name="last_chance_content",
            field=dataworkspace.apps.core.models.RichTextField(
                blank=True,
                help_text="(Optional) Message to run within 'last_chance_days' window.               Will be shown to users that have dismissed or not engaged with the banner.",
                null=True,
            ),
        ),
    ]
