# Generated by Django 4.2.18 on 2025-02-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification_banner", "0012_alter_notificationbanner_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationbanner",
            name="campaign_name",
            field=models.CharField(
                help_text="To be used as the cookie name(spaces will be removed on save)",
                max_length=255,
            ),
        ),
    ]
