# Generated by Django 2.2.10 on 2020-02-25 11:41

from django.db import migrations
from django.core.management.sql import emit_post_migrate_signal


def create_subject_matter_expert_group(app, schema_editor):
    # Trigger post-migrate steps, which will create custom model permissions
    # that otherwise might not be created if this migration runs in the same
    # migration group as the one which adds the permissions.
    # https://code.djangoproject.com/ticket/23422
    db_alias = schema_editor.connection.alias
    emit_post_migrate_signal(2, False, db_alias)

    Group = app.get_model('auth', 'Group')
    Permission = app.get_model('auth', 'Permission')
    sme = Group.objects.get_or_create(name="Subject Matter Experts")[0]
    perms = Permission.objects.filter(
        codename__in=[
            'manage_unpublished_master_datasets',
            'manage_unpublished_datacut_datasets',
        ]
    )
    sme.permissions.add(*perms)
    sme.save()


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "__latest__"),
        ("sites", "0001_initial"),
        ("datasets", "0038_add_permissions_and_customdatasetquery_defaults"),
    ]

    operations = [migrations.RunPython(create_subject_matter_expert_group)]
