# Generated by Django 2.2.10 on 2020-02-25 11:41
from django.db import migrations


def create_subject_matter_expert_group(app, schema_editor):
    # Code to create groups moved to post_migrate signal (in the datasets app)
    # to robustly run after the permission instances have been created
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0011_update_proxy_permissions"),
        ("datasets", "0038_add_permissions_and_customdatasetquery_defaults"),
    ]

    operations = [migrations.RunPython(create_subject_matter_expert_group)]
