# Generated by Django 3.2.19 on 2023-05-11 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_auto_20230511_1615"),
        ("finder", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasetfinderquerylog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="finder_searches",
                to="core.dataworkspaceuser",
            ),
        ),
    ]
