# Generated by Django 3.2.19 on 2023-05-31 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("finder", "0002_alter_datasetfinderquerylog_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasetfinderquerylog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="finder_searches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
