# Generated by Django 2.2.4 on 2019-08-12 12:51
import uuid

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'memorable_name',
                    models.CharField(
                        help_text='Must match the set of environment variables starting with DATA_DB__[memorable_name]__',
                        max_length=128,
                        unique=True,
                        validators=[django.core.validators.RegexValidator(regex='[A-Za-z0-9_]')],
                    ),
                ),
                (
                    'is_public',
                    models.BooleanField(
                        default=False,
                        help_text=(
                            'If public, the same credentials for the database will be shared with each user. '
                            'If not public, each user must be explicilty given access, '
                            'and temporary credentials will be created for each.'
                        ),
                    ),
                ),
            ],
            options={'db_table': 'app_database'},
        )
    ]
