# Generated by Django 3.0.8 on 2020-12-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_databaseuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databaseuser',
            name='deleted',
        ),
        migrations.AddField(
            model_name='databaseuser',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
