# Generated by Django 3.0.14 on 2021-05-17 15:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_auto_20210517_1501'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teammembership', unique_together={('team_id', 'user_id')},
        ),
    ]
