# Generated by Django 3.2.13 on 2022-05-30 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0008_newslettersubscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newslettersubscription",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="newsletter_signups",
                to=settings.AUTH_USER_MODEL,
                unique=True,
            ),
        ),
    ]
