# Generated by Django 3.2.13 on 2022-10-17 14:48

from django.db import migrations

from dataworkspace.apps.core.utils import update_tools_access_policy_task


def migrate_team_members(apps, _):
    """
    Loop through users with team membership and update their
    s3 perms to allow for team prefixes
    """
    users = apps.get_model("core", "TeamMembership").objects.values("user_id").distinct()
    for user in users:
        update_tools_access_policy_task.delay(user["user_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_mlflowauthoriseduser_mlflowinstance"),
    ]

    operations = [
        migrations.RunPython(migrate_team_members, migrations.RunPython.noop),
    ]
