# Generated by Django 3.2.19 on 2023-05-11 16:15

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0012_auto_20230425_1516"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataWorkspaceUser",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="mlflowauthoriseduser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authorised_mlflow_instances",
                to="core.dataworkspaceuser",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="member",
            field=models.ManyToManyField(
                through="core.TeamMembership", to="core.DataWorkspaceUser"
            ),
        ),
        migrations.AlterField(
            model_name="teammembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_memberships",
                to="core.dataworkspaceuser",
            ),
        ),
    ]
