# Generated by Django 3.2.19 on 2023-05-12 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_auto_20230511_1615"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chartbuilderchart",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created+",
                to="core.dataworkspaceuser",
            ),
        ),
        migrations.AlterField(
            model_name="chartbuilderchart",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated+",
                to="core.dataworkspaceuser",
            ),
        ),
        migrations.AlterField(
            model_name="databaseuser",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="db_user",
                to="core.dataworkspaceuser",
            ),
        ),
        migrations.AlterField(
            model_name="newslettersubscription",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="newsletter_signups",
                to="core.dataworkspaceuser",
                unique=True,
            ),
        ),
    ]
