# Generated by Django 3.2.19 on 2023-06-07 10:47

import dataworkspace.apps.core.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_auto_20230531_1549"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="notes",
            field=dataworkspace.apps.core.models.RichTextField(blank=True, null=True),
        ),
    ]
