# Generated by Django 3.2.20 on 2023-09-25 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0152_delete_datasetchartbuilderchart'),
        ('core', '0017_team_notes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChartBuilderChart',
        ),
    ]
