# Generated by Django 4.2.7 on 2024-01-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_delete_chartbuilderchart"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersatisfactionsurvey",
            name="describe_experience",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usersatisfactionsurvey",
            name="trying_to_do_other_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="usersatisfactionsurvey",
            name="trying_to_do",
            field=models.TextField(
                blank=True,
                choices=[
                    ("looking", "Looking for data"),
                    ("access-data", "Trying to access data"),
                    ("analyse-data", "Analyse data"),
                    ("share-date", "Share data"),
                    ("use-tool", "Use tools"),
                    ("create-visualisation", "Create a data visualisation"),
                    ("share-visualisation", "Share a data visualisation"),
                    ("view-visualisation", "View a data visualisation"),
                    ("support-guidance", "Looking for support or guidance"),
                    ("other", "Other"),
                ],
                null=True,
            ),
        ),
    ]
