# Generated by Django 4.2.11 on 2024-05-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_usersatisfactionsurvey_survey_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInlineFeedbackSurvey",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("location", models.CharField(max_length=256)),
                ("was_this_page_helpful", models.BooleanField()),
                ("inline_feedback_choices", models.TextField(blank=True, null=True)),
                ("more_detail", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
