# Generated by Django 4.2.14 on 2024-08-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_userinlinefeedbacksurvey"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="platform",
            field=models.CharField(
                choices=[
                    ("postgres", "Postgres"),
                    ("postgres-and-arango", "Postgres & ArangoDB"),
                ],
                default="postgres",
            ),
        ),
    ]
