# Generated by Django 2.1.2 on 2018-10-08 09:21

import uuid

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicDatabase',
            fields=[
                ('id', models.UUIDField(
                    default=uuid.uuid4,
                    editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('memorable_name', models.CharField(default='', max_length=128)),
                ('db_name', models.CharField(max_length=128)),
                ('db_host', models.CharField(max_length=128)),
                ('db_port', models.IntegerField(default=5432, validators=[
                    django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)])),
                ('db_user', models.CharField(max_length=128)),
                ('db_password', models.CharField(max_length=128)),
            ],
        ),
    ]
