# Generated by Django 2.2.4 on 2019-08-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_squashed_0038_alter_link_type_and_fill_with_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencedataset',
            name='licence',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
