# Generated by Django 2.1.2 on 2018-10-09 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PublicDatabase',
            new_name='Database',
        ),
    ]
