# Generated by Django 2.1.2 on 2018-10-09 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181009_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='db_host',
        ),
        migrations.RemoveField(
            model_name='database',
            name='db_name',
        ),
        migrations.RemoveField(
            model_name='database',
            name='db_password',
        ),
        migrations.RemoveField(
            model_name='database',
            name='db_port',
        ),
        migrations.RemoveField(
            model_name='database',
            name='db_user',
        ),
        migrations.AlterField(
            model_name='database',
            name='memorable_name',
            field=models.CharField(
                help_text='Must match the set of environment variables starting with DATA_DB__[memorable_name]__', max_length=128, validators=[
                    django.core.validators.RegexValidator(regex='[A-Za-z0-9_]')]),
        ),
    ]
