# Generated by Django 2.1.2 on 2018-10-10 08:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20181010_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='privilage',
            name='schema',
            field=models.CharField(
                default='public', max_length=1024, validators=[
                    django.core.validators.RegexValidator(regex='^[a-z][a-z0-9_]*$')]),
        ),
        migrations.AlterField(
            model_name='privilage',
            name='tables',
            field=models.CharField(
                help_text='Comma-separated list of tables that can be accessed on this schema. "ALL TABLES" (without quotes) to allow access to all tables.',
                max_length=1024, validators=[django.core.validators.RegexValidator(regex='(([a-z][a-z0-9_]*,?)+(?<!,)$)|(^ALL TABLES$)')]),
        ),
        migrations.AlterUniqueTogether(
            name='privilage',
            unique_together={('user', 'database', 'schema')},
        ),
    ]
