# Generated by Django 2.1.2 on 2019-03-07 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20181010_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privilage',
            name='schema',
            field=models.CharField(default='public', max_length=1024, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z][a-zA-Z0-9_\\.]*$')]),
        ),
        migrations.AlterField(
            model_name='privilage',
            name='tables',
            field=models.CharField(help_text='Comma-separated list of tables that can be accessed on this schema. "ALL TABLES" (without quotes) to allow access to all tables.', max_length=1024, validators=[django.core.validators.RegexValidator(regex='(([a-zA-Z][a-zA-Z0-9_\\.]*,?)+(?<!,)$)|(^ALL TABLES$)')]),
        ),
    ]
