# Generated by Django 2.1.2 on 2019-06-13 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190604_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationinstance',
            options={'permissions': [('start_all_applications', 'Can start all applications')]},
        ),
    ]
