# Generated by Django 2.1.2 on 2019-06-14 14:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190613_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataGrouping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('short_description', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('short_description', models.CharField(max_length=256)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('reference', models.CharField(max_length=128)),
                ('redactions', models.TextField(blank=True, null=True)),
                ('licence', models.CharField(blank=True, max_length=256, null=True)),
                ('volume', models.IntegerField()),
                ('retention_policy', models.TextField(blank=True, null=True)),
                ('personal_data', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResponsiblePerson',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='enquiries_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.ResponsiblePerson'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='grouping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.DataGrouping'),
        ),
        migrations.AddField(
            model_name='datagrouping',
            name='information_asset_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_manager', to='app.ResponsiblePerson'),
        ),
        migrations.AddField(
            model_name='datagrouping',
            name='information_asset_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_owner', to='app.ResponsiblePerson'),
        ),
    ]
