# Generated by Django 2.1.2 on 2019-06-14 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190613_1609'),
        ('app', '0009_auto_20190613_1452'),
    ]

    operations = [
    ]
