# Generated by Django 2.1.2 on 2019-06-17 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190613_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='memorable_name',
            field=models.CharField(help_text='Must match the set of environment variables starting with DATA_DB__[memorable_name]__', max_length=128, unique=True, validators=[django.core.validators.RegexValidator(regex='[A-Za-z0-9_]')]),
        ),
    ]
