# Generated by Django 2.1.2 on 2019-06-20 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_datagrouping_dataset_responsibleperson_sourcelink_sourceschema_sourcetables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datagrouping',
            name='audience',
        ),
    ]
