# Generated by Django 2.1.2 on 2019-06-14 15:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_dataset_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('format', models.CharField(max_length=10)),
                ('url', models.CharField(blank=True, max_length=1024, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('frequency', models.CharField(max_length=50)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.DataSet')),
                ('where_to_find', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Database')),
            ],
        ),
    ]
