# Generated by Django 2.1.2 on 2019-06-21 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_datagrouping_dataset_responsibleperson_sourcelink_sourceschema_sourcetables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourceschema',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sourcetables',
            name='name',
        ),
        migrations.AddField(
            model_name='sourceschema',
            name='database',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Database'),
        ),
        migrations.AddField(
            model_name='sourcetables',
            name='database',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Database'),
        ),
    ]
