# Generated by Django 2.1.2 on 2019-06-21 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_datagrouping_audience'),
        ('app', '0012_auto_20190621_0805'),
    ]

    operations = [
    ]
