# Generated by Django 2.1.2 on 2019-06-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('app', '0012_auto_20190621_0805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataset',
            options={'permissions': [('security_clearance', 'Security clearance')]},
        ),
        migrations.AddField(
            model_name='dataset',
            name='required_permissions',
            field=models.ManyToManyField(to='auth.Permission'),
        ),
    ]
