# Generated by Django 2.1.2 on 2019-06-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_datalink'),
    ]

    operations = [
        migrations.AddField(
            model_name='datagrouping',
            name='audience',
            field=models.TextField(blank=True, null=True),
        ),
    ]
