# Generated by Django 2.1.2 on 2019-06-21 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_merge_20190621_0847'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResponsiblePerson',
        ),
    ]
