# Generated by Django 2.1.2 on 2019-06-18 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_datagrouping_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datagrouping',
            name='information_asset_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_owner', to='app.ResponsiblePerson'),
        ),
    ]
