# Generated by Django 2.2.2 on 2019-06-24 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0014_delete_responsibleperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='user_access_type',
            field=models.CharField(choices=[('REQUIRES_AUTHENTICATION', 'Requires authentication'), ('REQUIRES_AUTHORIZATION', 'Requires authorization')], default='REQUIRES_AUTHENTICATION', max_length=64),
        ),
        migrations.CreateModel(
            name='DataSetUserPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.DataSet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'dataset')},
            },
        ),
    ]
