# Generated by Django 2.2.2 on 2019-06-25 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20190624_1527'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SourceTables',
        ),
    ]
