# Generated by Django 2.1.2 on 2019-06-18 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20190618_0945'),
        ('app', '0010_auto_20190617_1603'),
    ]

    operations = [
    ]
