# Generated by Django 2.2.2 on 2019-06-25 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_delete_sourcetables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privilage',
            name='tables',
        ),
    ]
