# Generated by Django 2.1.2 on 2019-07-01 15:38
import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20190626_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=1024)),
                ('key_field_name', models.CharField(max_length=128)),
                ('database', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Database')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.DataSet')),
            ],
        ),
    ]
