# Generated by Django 2.2.3 on 2019-07-07 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20190705_1257'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Privilage',
        ),
    ]
