# Generated by Django 2.1.2 on 2019-07-01 15:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_referencedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencedata',
            name='schema',
            field=models.CharField(default='public', max_length=1024, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z][a-zA-Z0-9_\\.]*$')]),
        ),
    ]
