# Generated by Django 2.1.2 on 2019-07-02 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_referencedata_schema'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referencedata',
            options={'verbose_name_plural': 'Reference data'},
        ),
        migrations.AddField(
            model_name='referencedata',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referencedata',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
