# Generated by Django 2.2.3 on 2019-07-09 11:57

import uuid

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_delete_privilage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
                ('schema', models.CharField(default='public', max_length=1024, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z][a-zA-Z0-9_\\.]*$')])),
                ('table', models.CharField(max_length=1024, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z][a-zA-Z0-9_\\.]*$')])),
                ('database', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Database')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.DataSet')),
            ],
        ),
    ]
