# Generated by Django 2.2.3 on 2019-07-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_sourcetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcelink',
            name='name',
            field=models.CharField(help_text='Used as the displayed text in the download link', max_length=128),
        ),
        migrations.AlterField(
            model_name='sourcetable',
            name='name',
            field=models.CharField(help_text='Used as the displayed text in the download link', max_length=1024),
        ),
    ]
