# Generated by Django 2.2.3 on 2019-07-09 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20190709_1203'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SourceSchema',
        ),
    ]
