# Generated by Django 2.2.3 on 2019-07-12 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_referencedataset_referencedatasetfield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referencedatasetfield',
            options={'ordering': ('id',), 'verbose_name': 'Reference Data Set Field'},
        ),
    ]
