# Generated by Django 2.2.3 on 2019-07-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20190712_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referencedataset',
            name='table_name',
        ),
        migrations.AlterField(
            model_name='referencedataset',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
