# Generated by Django 2.2.3 on 2019-07-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20190712_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='referencedataset',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
