# Generated by Django 2.2.3 on 2019-07-17 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20190712_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencedataset',
            name='licence',
            field=models.CharField(blank=True, default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='referencedatasetfield',
            name='name',
            field=models.CharField(help_text='The name of the field. May only contain lowercase letters numbers and underscores (no spaces)', max_length=60, validators=[django.core.validators.RegexValidator(message='Please only enter lowercase letters, numbers and underscores', regex='^[a-z][a-z0-9_\\.]*$')]),
        ),
    ]
