# Generated by Django 2.2.3 on 2019-07-17 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20190717_1320'),
        ('app', '0027_auto_20190717_1122'),
    ]

    operations = [
    ]
