# Generated by Django 2.2.3 on 2019-07-18 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20190717_1450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationinstance',
            options={'permissions': [('start_all_applications', 'Can start all applications'), ('access_appstream', 'Can access appstream')]},
        ),
    ]
