# Generated by Django 2.2.3 on 2019-07-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20190719_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencedataset',
            name='schema_version',
            field=models.IntegerField(default=0),
        ),
    ]
