# Generated by Django 2.2.3 on 2019-07-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_referencedataset_schema_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencedataset',
            name='major_version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='referencedataset',
            name='minor_version',
            field=models.IntegerField(default=0),
        ),
    ]
