# Generated by Django 2.2.3 on 2019-07-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20190725_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcelink',
            name='link_type',
            field=models.IntegerField(choices=[(1, 'External Link'), (2, 'Local Link')], default=1),
        ),
    ]
