# Generated by Django 2.2.3 on 2019-07-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20190727_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencedataset',
            name='major_version',
            field=models.IntegerField(default=1),
        ),
    ]
