# Generated by Django 2.2.3 on 2019-08-06 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20190725_1510'),
        ('app', '0035_auto_20190728_0641'),
    ]

    operations = [
    ]
