# Generated by Django 2.2.3 on 2019-08-07 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_sourcelink_link_type'),
        ('app', '0036_merge_20190806_0827'),
    ]

    operations = [
    ]
