export const FETCHED_PROFILE = 'FETCHED_PROFILE';
export const FETCH_PROFILE_ERROR = 'FETCH_PROFILE_ERROR';
export const OPEN_HOMEPAGE_MODAL = 'OPEN_HOMEPAGE_MODAL';
export const CLOSE_HOMEPAGE_MODAL = 'CLOSE_HOMEPAGE_MODAL';
export const IS_LOADING = 'IS_LOADING';
