# Generated by Django 3.0.14 on 2021-06-03 12:53

from django.db import migrations, models
import dataworkspace.apps.core.storage


class Migration(migrations.Migration):
    dependencies = [
        ("case_studies", "0002_auto_20210602_1557"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casestudy",
            name="image",
            field=models.ImageField(
                blank=True,
                storage=dataworkspace.apps.core.storage.S3FileStorage(),
                upload_to="",
            ),
        ),
    ]
