# Generated by Django 4.2.7 on 2024-03-15 14:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("case_studies", "0007_auto_20230531_1549"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CaseStudy",
        ),
    ]
