# Generated by Django 3.2.13 on 2022-05-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_access', '0002_alter_accessrequest_training_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='eligibility_criteria_met',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
