# Generated by Django 3.2.11 on 2022-01-27 13:58

import dataworkspace.apps.core.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("request_access", "0002_alter_accessrequest_training_screenshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="training_screenshot",
            field=models.FileField(
                blank=True,
                null=True,
                storage=dataworkspace.apps.core.storage.S3FileStorage(
                    location="training_screenshots"
                ),
                upload_to="",
                validators=[
                    dataworkspace.apps.core.storage.malware_file_validator,
                    django.core.validators.FileExtensionValidator(
                        ["bmp", "doc", "docx", "bmp", "jpeg", "jpg", "pdf"]
                    ),
                ],
            ),
        ),
    ]
