# Generated by Django 3.2.13 on 2022-07-18 14:22

from django.db import migrations, models
import dataworkspace.apps.core.storage


class Migration(migrations.Migration):

    dependencies = [
        ("request_access", "0003_accessrequest_eligibility_criteria_met"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="training_screenshot",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                storage=dataworkspace.apps.core.storage.S3FileStorage(
                    location="training_screenshots"
                ),
                upload_to="",
                validators=[dataworkspace.apps.core.storage.malware_file_validator],
            ),
        ),
    ]
