# Generated by Django 3.2.19 on 2023-05-12 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_migrate_auth_user_model"),
        ("request_access", "0004_alter_accessrequest_training_screenshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="requester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="access_requests",
                to="core.dataworkspaceuser",
            ),
        ),
    ]
