# Generated by Django 4.2.16 on 2024-10-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("request_access", "0006_alter_accessrequest_requester"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessrequest",
            name="data_access_status",
            field=models.CharField(
                choices=[
                    ("confirmed", "Confirmed"),
                    ("waiting", "Waiting"),
                    ("declined", "Declined"),
                ],
                max_length=256,
                null=True,
            ),
        ),
    ]
