# Generated by Django 3.2.20 on 2023-12-14 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("your_files", "0003_auto_20230531_1549"),
    ]

    operations = [
        migrations.CreateModel(
            name="YourFilesUserPrefixStats",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("prefix", models.CharField(db_index=True, max_length=255)),
                ("total_size_bytes", models.BigIntegerField()),
                ("num_files", models.IntegerField()),
                ("num_large_files", models.IntegerField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("last_checked_date", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="your_files_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_date",),
                "get_latest_by": "created_date",
            },
        ),
    ]
