# Generated by Django 2.1.2 on 2019-06-18 15:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataGrouping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('short_description', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('audience', models.TextField(blank=True, null=True)),
                ('information_asset_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_manager', to='catalogue.ResponsiblePerson')),
                ('information_asset_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_owner', to='catalogue.ResponsiblePerson')),
            ],
        ),
        migrations.CreateModel(
            name='DataLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('format', models.CharField(max_length=10)),
                ('url', models.CharField(blank=True, max_length=1024, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('frequency', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField()),
                ('short_description', models.CharField(max_length=256)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('reference', models.CharField(max_length=128)),
                ('redactions', models.TextField(blank=True, null=True)),
                ('licence', models.CharField(blank=True, max_length=256, null=True)),
                ('volume', models.IntegerField()),
                ('retention_policy', models.TextField(blank=True, null=True)),
                ('personal_data', models.CharField(blank=True, max_length=128, null=True)),
                ('enquiries_contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.ResponsiblePerson')),
                ('grouping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.DataGrouping')),
            ],
        ),
        migrations.AddField(
            model_name='datalink',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.DataSet'),
        ),
    ]
